#!/bin/sh

. /usr/share/initramfs-tools/hook-functions

if [ ! -x "/usr/libexec/ald-boot.sh" ]; then
    exit 0
fi
copy_exec /usr/libexec/ald-boot.sh /usr/libexec
copy_exec /usr/bin/hald /usr/bin
copy_exec /usr/bin/move-mount /usr/bin
copy_exec /usr/bin/bash /usr/bin
copy_exec /usr/bin/find /usr/bin
copy_exec /usr/bin/cat /usr/bin
copy_exec /usr/bin/chattr /usr/bin
copy_exec /usr/bin/dirname /usr/bin
copy_exec /usr/bin/echo /usr/bin
copy_exec /usr/bin/id /usr/bin
copy_exec /usr/bin/mount /usr/bin
copy_exec /usr/bin/mountpoint /usr/bin
copy_exec /usr/bin/mv /usr/bin
copy_exec /usr/bin/printf /usr/bin
copy_exec /usr/bin/rm /usr/bin
copy_exec /usr/bin/umount /usr/bin
