#!/usr/bin/env bash
set -oue pipefail

# -k should never be used with whald
if [[ "$1" == "--uki" ]]; then
    BUILD_UKI="y"
    shift
fi

case $1 in
    dep)
        :
        ;;
    *)
        printf "This script should only be used instead of hald dep!\n"
        exit 1
        ;;
esac

INITPREFIX="${INITPREFIX:-init}"
ALDPATH="${ALDPATH:-/.ald}"
BOOTPATH="${BOOTPATH:-/boot}"
UKIPATH="${UKIPATH:-/boot/EFI/Linux}"

hald "$@"

deployment="$(find "${BOOTPATH:?}" -maxdepth 1 -mindepth 1 -type d -name "[0-9]*" | rev | cut -d"/" -f1 | rev | sort -nr | head -n1)"
kver="$(ls "${ALDPATH:?}/${deployment:?}/usr/lib/modules")"

mount -o bind "${ALDPATH:?}/${deployment:?}/usr/lib/modules" /usr/lib/modules

rm -f "${BOOTPATH:?}/${deployment:?}/initramfs.img" || \
    { rm -rf "${BOOTPATH:?}/${deployment:?}" ; exit 1 ; }
mv -f "${BOOTPATH:?}/${deployment:?}/vmlinuz" "${BOOTPATH:?}/vmlinuz-$kver" || \
    { rm -rf "${BOOTPATH:?}/${deployment:?}"  "${BOOTPATH:?}/vmlinuz"* ; exit 1 ; }

update-initramfs -c -k all || \
    { rm -rf "${BOOTPATH:?}/${deployment:?}" "${BOOTPATH:?}/vmlinuz"* ; exit 1 ; }

mv -f "${BOOTPATH:?}/vmlinuz"* "${BOOTPATH:?}/${deployment:?}/vmlinuz" || \
    { rm -rf "${BOOTPATH:?}/${deployment:?}" "${BOOTPATH:?}/vmlinuz"* "${BOOTPATH:?}/$INITPREFIX"* ; exit 1 ; }
mv -f "${BOOTPATH:?}/$INITPREFIX"* "${BOOTPATH:?}/${deployment:?}/initramfs.img" || \
    { rm -rf "${BOOTPATH:?}/${deployment:?}" "${BOOTPATH:?}/vmlinuz"* "${BOOTPATH:?}/$INITPREFIX"* ; exit 1 ; }

umount -f /usr/lib/modules

if [[ "$BUILD_UKI" == "y" ]]; then
    CMDLINE="$(cat /etc/hald/cmdline | sed "s/INSERT_DEPLOYMENT/$deployment/" | tr -d "\n")"
    printf "UKI cmdline: %s\n" "$CMDLINE"
    ukify build --linux="${BOOTPATH:?}/${deployment:?}/vmlinuz" \
        --initrd="${BOOTPATH:?}/${deployment:?}/initramfs.img" \
        --cmdline="$CMDLINE" \
        --output="${UKIPATH:?}/${deployment:?}.efi"
    rm -rf "${BOOTPATH:?}/${deployment:?}"
    rm -f "${BOOTPATH:?}/loader/entries/${deployment:?}.conf"
fi
