name: build-hald-utils
on:
  pull_request:
    paths:
      - 'src/**'
      - 'utils/**'
      - 'Containerfile'
      - '.github/workflows/build-hald.yml'
      - 'hald.cabal'
  push:
    branches:
      - "main"
    paths:
      - 'src/**'
      - 'utils/**'
      - 'Containerfile'
      - '.github/workflows/build-hald.yml'
      - 'hald.cabal'
  schedule:
    - cron: '0 0 1 1/2 *'
  workflow_dispatch:

env:
    IMAGE_REGISTRY: docker.io/${{ github.repository_owner }}

jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Enable sigstore
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          IMAGE_REG: ${{ env.IMAGE_REGISTRY }}
        shell: bash
        run: |
          sudo mkdir -p /etc/containers/registries.d
          printf "docker:\n  %s:\n    use-sigstore-attachments: true\n" "$IMAGE_REG" \
            | sudo tee /etc/containers/registries.d/"$REPO_OWNER".yaml

      - name: Gather environment variables
        shell: bash
        run: |
          echo "IMAGE_NAME=hald-utils" >> $GITHUB_ENV

      - name: Generate tags
        id: generate-tags
        shell: bash
        run: |
          SRC="docker://${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}"
          echo "DATE_TAG=${SRC}:$(date +%Y%m%d)" >> $GITHUB_ENV
          echo "LATEST_TAG=${SRC}:latest" >> $GITHUB_ENV

      - name: Prepare signing key
        env:
          SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
        run: |
          mkdir -p /dev/shm/certs
          echo "$SIGNING_SECRET" > /dev/shm/certs/SIGNING_SECRET.key

      - name: Build image
        shell: bash
        run: |
          podman create --privileged -ti --name build \
            --mount type=bind,src=/dev/shm/certs,dst=/tmp/certs \
            --mount type=bind,src=/etc/containers/registries.d,dst=/etc/containers/registries.d \
            --mount type=bind,src=./Containerfile,dst=/Containerfile \
            --mount type=bind,src=cosign.pub,dst=/cosign.pub \
            --mount type=bind,src=hald.cabal,dst=/hald.cabal \
            --mount type=bind,src=cabal.project,dst=/cabal.project \
            --mount type=bind,src=CHANGELOG.md,dst=/CHANGELOG.md \
            --mount type=bind,src=LICENSE,dst=/LICENSE \
            --mount type=bind,src=src,dst=/src \
            --mount type=bind,src=utils,dst=/utils \
            quay.io/podman/stable:latest
          podman start build

          podman exec --privileged build \
            podman build --label=org.opencontainers.image.title=hald-utils \
            --label=org.opencontainers.image.description=hald-utils \
            --label=org.opencontainers.image.version=main \
            --pull=newer \
            --tag="localhost/hald-utils" \
            --target=target \
            --squash-all \
            --annotation=io.github.containers.compression.zstd=true \
            -f ./Containerfile

      - name: Push image
        if: github.event_name != 'pull_request'
        shell: bash
        run: |
          podman exec --privileged build \
            podman login --username="${{ github.actor }}" --password="${{ secrets.DOCKERHUB_TOKEN }}" docker.io

          push_tag() {
            TAG="$1"
            FAILED=()
            podman exec --privileged build \
              podman push "localhost/hald-utils" "${TAGS[$TAG]}" \
              --compression-format="zstd:chunked" --tls-verify=true \
              --sign-by-sigstore-private-key=/tmp/certs/SIGNING_SECRET.key || FAILED+=("$TAG")
            if [[ "${FAILED[*]}" == *"DATE"* ]]; then
              echo "Pushing "${TAGS[$TAG]}" failed!" && return 1
            elif [[ -n "${{ env.LATEST_TAG }}" && "${FAILED[*]}" == *"LATEST"* ]]; then
              echo "Pushing "${TAGS[$TAG]}" failed!" && return 1
            else echo ""${TAGS[$TAG]}" pushed successfully!" && return 0; fi
          }

          declare -A -r TAGS=(
            ["DATE"]="${{ env.DATE_TAG }}"
            ["LATEST"]="${{ env.LATEST_TAG }}"
          )
          for TAG in "${!TAGS[@]}"; do
            for try in {1..3}; do
              if push_tag "$TAG"; then break; fi
              echo "Try $try out of 3 exhausted!"
              sleep 15
            done
          done

          # Cleanup signing key
          podman exec build rm -f /tmp/certs/SIGNING_SECRET.key
          rm -f /dev/shm/certs/SIGNING_SECRET.key
